//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class CAP
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        string fIdentifier;
        /// <summary>
        ///Identifikátor
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Identifikátor")]
        public string Identifier
        {
            get
            {
                return fIdentifier;
            }

            set
            {
                SetPropertyValue<string>(nameof(Identifier), ref fIdentifier, value);
            }
        }

     
        string fNotifyHtml;
        /// <summary>
        ///Zpráva
        /// 
        /// </summary>
        [Index(0)]
        [Size(Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Zpráva")]
        public string NotifyHtml
        {
            get
            {
                return fNotifyHtml;
            }

            set
            {
                SetPropertyValue<string>(nameof(NotifyHtml), ref fNotifyHtml, value);
            }
        }


    }
}
