//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.INF.BO
{
    public partial class DestovaStanice
    {
        string fStationWSID;
        /// <summary>
        ///Station WSID
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Station WSID")]
        public string StationWSID
        {
            get
            {
                return fStationWSID;
            }

            set
            {
                SetPropertyValue<string>(nameof(StationWSID), ref fStationWSID, value);
            }
        }

     
        string fGHID;
        /// <summary>
        ///Hydrologický identifikátor
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Hydrologický identifikátor")]
        public string GHID
        {
            get
            {
                return fGHID;
            }

            set
            {
                SetPropertyValue<string>(nameof(GHID), ref fGHID, value);
            }
        }

     
        string fWSI;
        /// <summary>
        ///Meteorologický identifikátor
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Meteorologický identifikátor")]
        public string WSI
        {
            get
            {
                return fWSI;
            }

            set
            {
                SetPropertyValue<string>(nameof(WSI), ref fWSI, value);
            }
        }


    }
}
