//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class DPK
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fCreateDate;
        /// <summary>
        ///Datum vytvoření
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum vytvoření")]
        public DateTime CreateDate
        {
            get
            {
                return fCreateDate;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(CreateDate), ref fCreateDate, value);
            }
        }

     
        string fEvidentNumber;
        /// <summary>
        ///Evidenční číslo
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Evidenční číslo")]
        public string EvidentNumber
        {
            get
            {
                return fEvidentNumber;
            }

            set
            {
                SetPropertyValue<string>(nameof(EvidentNumber), ref fEvidentNumber, value);
            }
        }

     
        string fNotice;
        /// <summary>
        ///Poznámka
        /// 
        /// </summary>
        [Index(0)]
        [Size(Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Poznámka")]
        public string Notice
        {
            get
            {
                return fNotice;
            }

            set
            {
                SetPropertyValue<string>(nameof(Notice), ref fNotice, value);
            }
        }

     
        GA_User fPracovnik;
        /// <summary>
        ///Pracovník
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Pracovník")]
        public GA_User Pracovnik
        {
            get
            {
                return fPracovnik;
            }

            set
            {
                SetPropertyValue<GA_User>(nameof(Pracovnik), ref fPracovnik, value);
            }
        }


    }
}
