//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class DPK_CAP
    {
        PIS_CAP fCAPRecord;
        /// <summary>
        ///CAP záznam
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"CAP záznam")]
        public PIS_CAP CAPRecord
        {
            get
            {
                return fCAPRecord;
            }

            set
            {
                SetPropertyValue<PIS_CAP>(nameof(CAPRecord), ref fCAPRecord, value);
            }
        }


    }
}
