//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class DPK_PISObject
    {
        PIS_VObject fPISObject;
        /// <summary>
        ///Virtu�ln� objekt
        /// 
        /// </summary>
        [Association(name = DPKRefVObject)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Virtu�ln� objekt")]
        public PIS_VObject PISObject
        {
            get
            {
                return fPISObject;
            }

            set
            {
                SetPropertyValue<PIS_VObject>(nameof(PISObject), ref fPISObject, value);
            }
        }

     
        PIS_NotifikaceLimitu fNotifikaceLimitu;
        /// <summary>
        ///Limit
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Limit")]
        public PIS_NotifikaceLimitu NotifikaceLimitu
        {
            get
            {
                return fNotifikaceLimitu;
            }

            set
            {
                SetPropertyValue<PIS_NotifikaceLimitu>(nameof(NotifikaceLimitu), ref fNotifikaceLimitu, value);
            }
        }


    }
}
