//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.ConditionalAppearance;
using GA.PIS;

namespace GA.PIS.BO
{
    /// <summary>
    /// 
    /// </summary>
    [Persistent(@"pis_DPK_GIS")]
    public partial class DPK_GIS : GA.PIS.BO.PIS_DPK
    {
        /// <summary>
        /// Konstruktor třídy - sem se NIC nepíše!
        /// </summary>
        public DPK_GIS(Session session) : base(session)
        {
        }

        /// <summary>
        /// Automaticky generovaný AfterConstruction - Zde se doplňují DefaultValues z CML
        /// </summary>
        protected void GeneratedAfterConstructionDPK_GIS()
        {
            /*base.AfterConstruction();*/
        }

        /// <summary>
        /// Automaticky generovaný PripravAgregace
        /// </summary>
        protected void GeneratedPripravAgregaceDPK_GIS()
        {
        }
    }
}

