//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.INF.BO
{
    public partial class HlasnyProfil
    {
        string fCentrumAutomatickehoSberuDat;
        /// <summary>
        ///Centrum automatického sběru dat
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Centrum automatického sběru dat")]
        public string CentrumAutomatickehoSberuDat
        {
            get
            {
                return fCentrumAutomatickehoSberuDat;
            }

            set
            {
                SetPropertyValue<string>(nameof(CentrumAutomatickehoSberuDat), ref fCentrumAutomatickehoSberuDat, value);
            }
        }

     
        int fCetnostHlaseniSPAI;
        /// <summary>
        ///Četnost 1.SPA (Bdělost) [cm]
        /// 
        /// </summary>
        [cm]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Četnost 1.SPA (Bdělost) [cm]")]
        public int CetnostHlaseniSPAI
        {
            get
            {
                return fCetnostHlaseniSPAI;
            }

            set
            {
                SetPropertyValue<int>(nameof(CetnostHlaseniSPAI), ref fCetnostHlaseniSPAI, value);
            }
        }

     
        int fCetnostHlaseniSPAII;
        /// <summary>
        ///Četnost 2.SPA (Pohotovost) [cm]
        /// 
        /// </summary>
        [cm]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Četnost 2.SPA (Pohotovost) [cm]")]
        public int CetnostHlaseniSPAII
        {
            get
            {
                return fCetnostHlaseniSPAII;
            }

            set
            {
                SetPropertyValue<int>(nameof(CetnostHlaseniSPAII), ref fCetnostHlaseniSPAII, value);
            }
        }

     
        int fCetnostHlaseniSPAIII;
        /// <summary>
        ///Četnost 3.SPA (Extrémní povodeň) [cm]
        /// 
        /// </summary>
        [cm]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Četnost 3.SPA (Extrémní povodeň) [cm]")]
        public int CetnostHlaseniSPAIII
        {
            get
            {
                return fCetnostHlaseniSPAIII;
            }

            set
            {
                SetPropertyValue<int>(nameof(CetnostHlaseniSPAIII), ref fCetnostHlaseniSPAIII, value);
            }
        }

     
        string fCisloHydrologickehoPoradi;
        /// <summary>
        ///Číslo hydrologického pořadí
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Číslo hydrologického pořadí")]
        public string CisloHydrologickehoPoradi
        {
            get
            {
                return fCisloHydrologickehoPoradi;
            }

            set
            {
                SetPropertyValue<string>(nameof(CisloHydrologickehoPoradi), ref fCisloHydrologickehoPoradi, value);
            }
        }

     
        string fCisloHydroPoradi;
        /// <summary>
        ///Číslo hydrologického pořadí
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Číslo hydrologického pořadí")]
        public string CisloHydroPoradi
        {
            get
            {
                return fCisloHydroPoradi;
            }

            set
            {
                SetPropertyValue<string>(nameof(CisloHydroPoradi), ref fCisloHydroPoradi, value);
            }
        }

     
        int fCoordinateX;
        /// <summary>
        ///Souřadnice X
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Souřadnice X")]
        public int CoordinateX
        {
            get
            {
                return fCoordinateX;
            }

            set
            {
                SetPropertyValue<int>(nameof(CoordinateX), ref fCoordinateX, value);
            }
        }

     
        int fCoordinateY;
        /// <summary>
        ///Souřadnice Y
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Souřadnice Y")]
        public int CoordinateY
        {
            get
            {
                return fCoordinateY;
            }

            set
            {
                SetPropertyValue<int>(nameof(CoordinateY), ref fCoordinateY, value);
            }
        }

     
        string fEvidencniListHP;
        /// <summary>
        ///Evidenční list hlásného profilu
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Evidenční list hlásného profilu")]
        public string EvidencniListHP
        {
            get
            {
                return fEvidencniListHP;
            }

            set
            {
                SetPropertyValue<string>(nameof(EvidencniListHP), ref fEvidencniListHP, value);
            }
        }

     
        decimal fHladina;
        /// <summary>
        ///Hladina
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = #########0.00## cm)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hladina")]
        public decimal Hladina
        {
            get
            {
                return fHladina;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Hladina), ref fHladina, value);
            }
        }

     
        string fKategorieStanice;
        /// <summary>
        ///Kategorie stanice
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Kategorie stanice")]
        public string KategorieStanice
        {
            get
            {
                return fKategorieStanice;
            }

            set
            {
                SetPropertyValue<string>(nameof(KategorieStanice), ref fKategorieStanice, value);
            }
        }

     
        ADR_Kraj fKraj;
        /// <summary>
        ///Kraj
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Kraj")]
        public ADR_Kraj Kraj
        {
            get
            {
                return fKraj;
            }

            set
            {
                SetPropertyValue<ADR_Kraj>(nameof(Kraj), ref fKraj, value);
            }
        }

     
        string fKritickeMisto;
        /// <summary>
        ///Kritické míisto
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Kritické míisto")]
        public string KritickeMisto
        {
            get
            {
                return fKritickeMisto;
            }

            set
            {
                SetPropertyValue<string>(nameof(KritickeMisto), ref fKritickeMisto, value);
            }
        }

     
        DateTime fLastDatum;
        /// <summary>
        ///Datum posledního odečtu
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum posledního odečtu")]
        public DateTime LastDatum
        {
            get
            {
                return fLastDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(LastDatum), ref fLastDatum, value);
            }
        }

     
        decimal fNejvyssiZaznamenaneStavy;
        /// <summary>
        ///Nejvyšší zaznamenané stavy
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = #########0.00## cm)]
        [ModelDefault(EditMask = N4)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Nejvyšší zaznamenané stavy")]
        public decimal NejvyssiZaznamenaneStavy
        {
            get
            {
                return fNejvyssiZaznamenaneStavy;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NejvyssiZaznamenaneStavy), ref fNejvyssiZaznamenaneStavy, value);
            }
        }

     
        DateTime fNejvyssiZaznamenaneStavyDatum;
        /// <summary>
        ///Nejvyšší zaznamenané stavy datum
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Nejvyšší zaznamenané stavy datum")]
        public DateTime NejvyssiZaznamenaneStavyDatum
        {
            get
            {
                return fNejvyssiZaznamenaneStavyDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(NejvyssiZaznamenaneStavyDatum), ref fNejvyssiZaznamenaneStavyDatum, value);
            }
        }

     
        decimal fNLetePrutokyQ1;
        /// <summary>
        ///NLeté průtoky Q1
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q1")]
        public decimal NLetePrutokyQ1
        {
            get
            {
                return fNLetePrutokyQ1;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ1), ref fNLetePrutokyQ1, value);
            }
        }

     
        decimal fNLetePrutokyQ10;
        /// <summary>
        ///NLeté průtoky Q10
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q10")]
        public decimal NLetePrutokyQ10
        {
            get
            {
                return fNLetePrutokyQ10;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ10), ref fNLetePrutokyQ10, value);
            }
        }

     
        decimal fNLetePrutokyQ100;
        /// <summary>
        ///NLeté průtoky Q100
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q100")]
        public decimal NLetePrutokyQ100
        {
            get
            {
                return fNLetePrutokyQ100;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ100), ref fNLetePrutokyQ100, value);
            }
        }

     
        decimal fNLetePrutokyQ2;
        /// <summary>
        ///NLeté průtoky Q2
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q2")]
        public decimal NLetePrutokyQ2
        {
            get
            {
                return fNLetePrutokyQ2;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ2), ref fNLetePrutokyQ2, value);
            }
        }

     
        decimal fNLetePrutokyQ20;
        /// <summary>
        ///NLeté průtoky Q20
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q20")]
        public decimal NLetePrutokyQ20
        {
            get
            {
                return fNLetePrutokyQ20;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ20), ref fNLetePrutokyQ20, value);
            }
        }

     
        decimal fNLetePrutokyQ355;
        /// <summary>
        ///NLeté průtoky Q355
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q355")]
        public decimal NLetePrutokyQ355
        {
            get
            {
                return fNLetePrutokyQ355;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ355), ref fNLetePrutokyQ355, value);
            }
        }

     
        decimal fNLetePrutokyQ5;
        /// <summary>
        ///NLeté průtoky Q5
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q5")]
        public decimal NLetePrutokyQ5
        {
            get
            {
                return fNLetePrutokyQ5;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ5), ref fNLetePrutokyQ5, value);
            }
        }

     
        decimal fNLetePrutokyQ50;
        /// <summary>
        ///NLeté průtoky Q50
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N3} m/s)]
        [ModelDefault(EditMask = {0:N3} m/s)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"NLeté průtoky Q50")]
        public decimal NLetePrutokyQ50
        {
            get
            {
                return fNLetePrutokyQ50;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NLetePrutokyQ50), ref fNLetePrutokyQ50, value);
            }
        }

     
        decimal fNulaVodoctu;
        /// <summary>
        ///Nula vodočtu
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = N2)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Nula vodočtu")]
        public decimal NulaVodoctu
        {
            get
            {
                return fNulaVodoctu;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(NulaVodoctu), ref fNulaVodoctu, value);
            }
        }

     
        ADR_Obec fObec;
        /// <summary>
        ///Obec
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Obec")]
        public ADR_Obec Obec
        {
            get
            {
                return fObec;
            }

            set
            {
                SetPropertyValue<ADR_Obec>(nameof(Obec), ref fObec, value);
            }
        }

     
        ADR_Obec fORP;
        /// <summary>
        ///ORP
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"ORP")]
        public ADR_Obec ORP
        {
            get
            {
                return fORP;
            }

            set
            {
                SetPropertyValue<ADR_Obec>(nameof(ORP), ref fORP, value);
            }
        }

     
        string fPlatnostSPAProUsekToku;
        /// <summary>
        ///Platnost SPA pro úsek toku
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Platnost SPA pro úsek toku")]
        public string PlatnostSPAProUsekToku
        {
            get
            {
                return fPlatnostSPAProUsekToku;
            }

            set
            {
                SetPropertyValue<string>(nameof(PlatnostSPAProUsekToku), ref fPlatnostSPAProUsekToku, value);
            }
        }

     
        decimal fPlochaPovodi;
        /// <summary>
        ///Plocha povodí
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = #########0.00## km)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Plocha povodí")]
        public decimal PlochaPovodi
        {
            get
            {
                return fPlochaPovodi;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(PlochaPovodi), ref fPlochaPovodi, value);
            }
        }

     
        string fPopisUmisteniProfilu;
        /// <summary>
        ///Popis umístění profilu
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Popis umístění profilu")]
        public string PopisUmisteniProfilu
        {
            get
            {
                return fPopisUmisteniProfilu;
            }

            set
            {
                SetPropertyValue<string>(nameof(PopisUmisteniProfilu), ref fPopisUmisteniProfilu, value);
            }
        }

     
        string fPoznamka;
        /// <summary>
        ///Poznámka
        /// 
        /// </summary>
        [Index(0)]
        [Size(Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Poznámka")]
        public string Poznamka
        {
            get
            {
                return fPoznamka;
            }

            set
            {
                SetPropertyValue<string>(nameof(Poznamka), ref fPoznamka, value);
            }
        }

     
        decimal fProcentoPlochyPovodiToku;
        /// <summary>
        ///Procento plochy povodi toku
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = ####0.00## %)]
        [ModelDefault(EditMask = N2)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Procento plochy povodi toku")]
        public decimal ProcentoPlochyPovodiToku
        {
            get
            {
                return fProcentoPlochyPovodiToku;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(ProcentoPlochyPovodiToku), ref fProcentoPlochyPovodiToku, value);
            }
        }

     
        decimal fPrumernyRocniPrutok;
        /// <summary>
        ///Průměrný roční průtok
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = N2)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Průměrný roční průtok")]
        public decimal PrumernyRocniPrutok
        {
            get
            {
                return fPrumernyRocniPrutok;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(PrumernyRocniPrutok), ref fPrumernyRocniPrutok, value);
            }
        }

     
        decimal fPrumernyRocniStav;
        /// <summary>
        ///Průměrný ročni stav
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = N2)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Průměrný ročni stav")]
        public decimal PrumernyRocniStav
        {
            get
            {
                return fPrumernyRocniStav;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(PrumernyRocniStav), ref fPrumernyRocniStav, value);
            }
        }

     
        decimal fPrutok;
        /// <summary>
        ///Průtok
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = ### ### ##0.####)]
        [ModelDefault(EditMask = N2)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Průtok")]
        public decimal Prutok
        {
            get
            {
                return fPrutok;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Prutok), ref fPrutok, value);
            }
        }

     
        decimal fStaniceni;
        /// <summary>
        ///Staničení
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = N2)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Staničení")]
        public decimal Staniceni
        {
            get
            {
                return fStaniceni;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Staniceni), ref fStaniceni, value);
            }
        }

     
        string fStationWSID;
        /// <summary>
        ///Station WSID
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Station WSID")]
        public string StationWSID
        {
            get
            {
                return fStationWSID;
            }

            set
            {
                SetPropertyValue<string>(nameof(StationWSID), ref fStationWSID, value);
            }
        }

     
        decimal fTeplota;
        /// <summary>
        ///Teplota
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = N2)]
        [Index(0)]
        public decimal Teplota
        {
            get
            {
                return fTeplota;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Teplota), ref fTeplota, value);
            }
        }

     
        PIS_Reka fTok;
        /// <summary>
        ///Tok
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Tok")]
        public PIS_Reka Tok
        {
            get
            {
                return fTok;
            }

            set
            {
                SetPropertyValue<PIS_Reka>(nameof(Tok), ref fTok, value);
            }
        }

     
        decimal fZemepisneSouradniceX;
        /// <summary>
        ///Zeměpisné souřadniceX
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = N7)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Zeměpisné souřadniceX")]
        public decimal ZemepisneSouradniceX
        {
            get
            {
                return fZemepisneSouradniceX;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(ZemepisneSouradniceX), ref fZemepisneSouradniceX, value);
            }
        }

     
        decimal fZemepisneSouradniceY;
        /// <summary>
        ///Zeměpisné souřadniceY
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0})]
        [ModelDefault(EditMask = N7)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Zeměpisné souřadniceY")]
        public decimal ZemepisneSouradniceY
        {
            get
            {
                return fZemepisneSouradniceY;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(ZemepisneSouradniceY), ref fZemepisneSouradniceY, value);
            }
        }

     
        string fBasicUrl;
        /// <summary>
        ///BasicUrl
        /// 
        /// </summary>
        [Browsable(false)]
        [DevExpress.Xpo.DisplayName(@"BasicUrl")]
        public string BasicUrl
        {
            get
            {
                return fBasicUrl;
            }

            set
            {
                SetPropertyValue<string>(nameof(BasicUrl), ref fBasicUrl, value);
            }
        }


    }
}
