//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class LimitNonSPA1
    {
        PIS_VObject fVobject;
        /// <summary>
        ///Virtuální objekt
        /// 
        /// </summary>
        [Association(name = LimitNonSPA1RefVObject)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Virtuální objekt")]
        public PIS_VObject Vobject
        {
            get
            {
                return fVobject;
            }

            set
            {
                SetPropertyValue<PIS_VObject>(nameof(Vobject), ref fVobject, value);
            }
        }


    }
}
