//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class Limit
    {
        e_StylCary fDashStyle;
        /// <summary>
        ///DashStyle
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"DashStyle")]
        public e_StylCary DashStyle
        {
            get
            {
                return fDashStyle;
            }

            set
            {
                SetPropertyValue<e_StylCary>(nameof(DashStyle), ref fDashStyle, value);
            }
        }

     
        decimal fHodnota;
        /// <summary>
        ///Hodnota
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = #########0.00## cm)]
        [RuleRequiredField(RuleRequiredField for PIS_Hodnota)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hodnota")]
        public decimal Hodnota
        {
            get
            {
                return fHodnota;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Hodnota), ref fHodnota, value);
            }
        }

     
        bool fJePrvniSPA;
        /// <summary>
        ///JePrvniSPA
        /// 
        /// </summary>
        [Index(0)]
        public bool JePrvniSPA
        {
            get
            {
                return fJePrvniSPA;
            }

            set
            {
                SetPropertyValue<bool>(nameof(JePrvniSPA), ref fJePrvniSPA, value);
            }
        }

     
        string fNazevLimitu;
        /// <summary>
        ///Název limitu
        /// 
        /// </summary>
        [RuleRequiredField(RuleRequiredField for PIS_NazevLimitu)]
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Název limitu")]
        public string NazevLimitu
        {
            get
            {
                return fNazevLimitu;
            }

            set
            {
                SetPropertyValue<string>(nameof(NazevLimitu), ref fNazevLimitu, value);
            }
        }

     
        string fNoticeLimit;
        /// <summary>
        ///Poznámka
        /// 
        /// </summary>
        [Index(0)]
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Poznámka")]
        public string NoticeLimit
        {
            get
            {
                return fNoticeLimit;
            }

            set
            {
                SetPropertyValue<string>(nameof(NoticeLimit), ref fNoticeLimit, value);
            }
        }

     
        int fTloustka;
        /// <summary>
        ///Tloustka
        /// 
        /// </summary>
        [Index(0)]
        public int Tloustka
        {
            get
            {
                return fTloustka;
            }

            set
            {
                SetPropertyValue<int>(nameof(Tloustka), ref fTloustka, value);
            }
        }

     
        e_TypLimitu fTyp;
        /// <summary>
        ///Typ limitu
        /// 
        /// </summary>
        [RuleRequiredField(RuleRequiredField for PIS_Limit.Typ)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Typ limitu")]
        public e_TypLimitu Typ
        {
            get
            {
                return fTyp;
            }

            set
            {
                SetPropertyValue<e_TypLimitu>(nameof(Typ), ref fTyp, value);
            }
        }

     
        bool fZobrazitVGrafu;
        /// <summary>
        ///ZobrazitVGrafu
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"ZobrazitVGrafu")]
        public bool ZobrazitVGrafu
        {
            get
            {
                return fZobrazitVGrafu;
            }

            set
            {
                SetPropertyValue<bool>(nameof(ZobrazitVGrafu), ref fZobrazitVGrafu, value);
            }
        }

     
        Color fBarva;
        /// <summary>
        ///Barva
        /// 
        /// </summary>
        [VisibleInListView(true)]
        public Color Barva
        {
            get
            {
                return fBarva;
            }

            set
            {
                SetPropertyValue<Color>(nameof(Barva), ref fBarva, value);
            }
        }


    }
}
