//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class NotifikaceLimitu
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        PIS_Limit fLimit;
        /// <summary>
        ///Limit
        /// 
        /// </summary>
        [Association(name = NLRefLimit)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Limit")]
        public PIS_Limit Limit
        {
            get
            {
                return fLimit;
            }

            set
            {
                SetPropertyValue<PIS_Limit>(nameof(Limit), ref fLimit, value);
            }
        }

     
        e_TypeOfNotificationLimit fType;
        /// <summary>
        ///Typ notifikace
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Typ notifikace")]
        public e_TypeOfNotificationLimit Type
        {
            get
            {
                return fType;
            }

            set
            {
                SetPropertyValue<e_TypeOfNotificationLimit>(nameof(Type), ref fType, value);
            }
        }

     
        e_WayOfLimit fWay;
        /// <summary>
        ///Typ limitu
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Typ limitu")]
        public e_WayOfLimit Way
        {
            get
            {
                return fWay;
            }

            set
            {
                SetPropertyValue<e_WayOfLimit>(nameof(Way), ref fWay, value);
            }
        }


    }
}
