//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class NotifikaceLimituZadost
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        decimal fAktualniHodnota;
        /// <summary>
        ///Aktuální hodnota
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Aktuální hodnota")]
        public decimal AktualniHodnota
        {
            get
            {
                return fAktualniHodnota;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(AktualniHodnota), ref fAktualniHodnota, value);
            }
        }

     
        DateTime fDatumHodnoty;
        /// <summary>
        ///Datum hodnoty
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum hodnoty")]
        public DateTime DatumHodnoty
        {
            get
            {
                return fDatumHodnoty;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(DatumHodnoty), ref fDatumHodnoty, value);
            }
        }

     
        DateTime fDatumZadosti;
        /// <summary>
        ///Datum žádosti
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum žádosti")]
        public DateTime DatumZadosti
        {
            get
            {
                return fDatumZadosti;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(DatumZadosti), ref fDatumZadosti, value);
            }
        }

     
        DateTime fDatumZaslani;
        /// <summary>
        ///Datum zaslání
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum zaslání")]
        public DateTime DatumZaslani
        {
            get
            {
                return fDatumZaslani;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(DatumZaslani), ref fDatumZaslani, value);
            }
        }

     
        PIS_HlasnyProfil fHlasnyProfil;
        /// <summary>
        ///Hlásný profil
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hlásný profil")]
        public PIS_HlasnyProfil HlasnyProfil
        {
            get
            {
                return fHlasnyProfil;
            }

            set
            {
                SetPropertyValue<PIS_HlasnyProfil>(nameof(HlasnyProfil), ref fHlasnyProfil, value);
            }
        }

     
        PIS_NotifikaceLimitu fNotificationLimit;
        /// <summary>
        ///Notifikace limitu
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Notifikace limitu")]
        public PIS_NotifikaceLimitu NotificationLimit
        {
            get
            {
                return fNotificationLimit;
            }

            set
            {
                SetPropertyValue<PIS_NotifikaceLimitu>(nameof(NotificationLimit), ref fNotificationLimit, value);
            }
        }

     
        e_StatusNotifikace fStatus;
        /// <summary>
        ///Status
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Status")]
        public e_StatusNotifikace Status
        {
            get
            {
                return fStatus;
            }

            set
            {
                SetPropertyValue<e_StatusNotifikace>(nameof(Status), ref fStatus, value);
            }
        }

     
        NotifiableRuleSet fNotifiableRule;
        /// <summary>
        ///Notifikovaní
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Notifikovaní")]
        public NotifiableRuleSet NotifiableRule
        {
            get
            {
                return fNotifiableRule;
            }

            set
            {
                SetPropertyValue<NotifiableRuleSet>(nameof(NotifiableRule), ref fNotifiableRule, value);
            }
        }

     
        PIS_VObject fVObject;
        /// <summary>
        ///PIS Object
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"PIS Object")]
        public PIS_VObject VObject
        {
            get
            {
                return fVObject;
            }

            set
            {
                SetPropertyValue<PIS_VObject>(nameof(VObject), ref fVObject, value);
            }
        }


    }
}
