//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class OdecetDS
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fDatum;
        /// <summary>
        ///Datum a čas
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum a čas")]
        public DateTime Datum
        {
            get
            {
                return fDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value);
            }
        }

     
        double fHodnota;
        /// <summary>
        ///Hodnota
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = N3)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hodnota")]
        public double Hodnota
        {
            get
            {
                return fHodnota;
            }

            set
            {
                SetPropertyValue<double>(nameof(Hodnota), ref fHodnota, value);
            }
        }

     
        PIS_DestovaStanice fStanice;
        /// <summary>
        ///Dešťová stanice
        /// 
        /// </summary>
        [Association(name = OdectyRefDS)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Dešťová stanice")]
        public PIS_DestovaStanice Stanice
        {
            get
            {
                return fStanice;
            }

            set
            {
                SetPropertyValue<PIS_DestovaStanice>(nameof(Stanice), ref fStanice, value);
            }
        }


    }
}
