//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class OdecetVS
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fDatum;
        /// <summary>
        ///Datum a čas
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum a čas")]
        public DateTime Datum
        {
            get
            {
                return fDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value);
            }
        }

     
        double fHladina;
        /// <summary>
        ///Hladina
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0} cm)]
        [ModelDefault(EditMask = N0)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hladina")]
        public double Hladina
        {
            get
            {
                return fHladina;
            }

            set
            {
                SetPropertyValue<double>(nameof(Hladina), ref fHladina, value);
            }
        }

     
        double fHladinaRucne;
        /// <summary>
        ///Hladina ručně
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0} cm)]
        [ModelDefault(EditMask = N0)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hladina ručně")]
        public double HladinaRucne
        {
            get
            {
                return fHladinaRucne;
            }

            set
            {
                SetPropertyValue<double>(nameof(HladinaRucne), ref fHladinaRucne, value);
            }
        }

     
        PIS_HlasnyProfil fHlasnyProfil;
        /// <summary>
        ///Hlásný profil
        /// 
        /// </summary>
        [Association(name = OdectyRefHP)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hlásný profil")]
        public PIS_HlasnyProfil HlasnyProfil
        {
            get
            {
                return fHlasnyProfil;
            }

            set
            {
                SetPropertyValue<PIS_HlasnyProfil>(nameof(HlasnyProfil), ref fHlasnyProfil, value);
            }
        }

     
        string fPoznamka;
        /// <summary>
        ///Poznámka
        /// 
        /// </summary>
        [Index(0)]
        [Size(Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Poznámka")]
        public string Poznamka
        {
            get
            {
                return fPoznamka;
            }

            set
            {
                SetPropertyValue<string>(nameof(Poznamka), ref fPoznamka, value);
            }
        }

     
        double fPrutok;
        /// <summary>
        ///Průtok
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Průtok")]
        public double Prutok
        {
            get
            {
                return fPrutok;
            }

            set
            {
                SetPropertyValue<double>(nameof(Prutok), ref fPrutok, value);
            }
        }

     
        double fTeplota;
        /// <summary>
        ///Teplota
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Teplota")]
        public double Teplota
        {
            get
            {
                return fTeplota;
            }

            set
            {
                SetPropertyValue<double>(nameof(Teplota), ref fTeplota, value);
            }
        }

     
        e_TypeOfOdecet fTyp;
        /// <summary>
        ///Typ záznamu
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Typ záznamu")]
        public e_TypeOfOdecet Typ
        {
            get
            {
                return fTyp;
            }

            set
            {
                SetPropertyValue<e_TypeOfOdecet>(nameof(Typ), ref fTyp, value);
            }
        }

     
        double fFAKESPA;
        /// <summary>
        ///FAKESPA
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        public double FAKESPA
        {
            get
            {
                return fFAKESPA;
            }

            set
            {
                SetPropertyValue<double>(nameof(FAKESPA), ref fFAKESPA, value);
            }
        }

     
        PIS_Limit fSPAachieved;
        /// <summary>
        ///SPAachieved
        /// 
        /// </summary>
        public PIS_Limit SPAachieved
        {
            get
            {
                return fSPAachieved;
            }

            set
            {
                SetPropertyValue<PIS_Limit>(nameof(SPAachieved), ref fSPAachieved, value);
            }
        }


    }
}
