//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class OdecetVS_his
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fDatum;
        /// <summary>
        ///Datum
        /// 
        /// </summary>
        [Index(0)]
        public DateTime Datum
        {
            get
            {
                return fDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value);
            }
        }

     
        double fHladina;
        /// <summary>
        ///Hladina
        /// 
        /// </summary>
        [Index(0)]
        public double Hladina
        {
            get
            {
                return fHladina;
            }

            set
            {
                SetPropertyValue<double>(nameof(Hladina), ref fHladina, value);
            }
        }

     
        double fHladinaRucne;
        /// <summary>
        ///Hladina ručně
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hladina ručně")]
        public double HladinaRucne
        {
            get
            {
                return fHladinaRucne;
            }

            set
            {
                SetPropertyValue<double>(nameof(HladinaRucne), ref fHladinaRucne, value);
            }
        }

     
        PIS_HlasnyProfil fHlasnyProfil;
        /// <summary>
        ///Hlásný profil
        /// 
        /// </summary>
        [Association(name = OdectyHisRefHP)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hlásný profil")]
        public PIS_HlasnyProfil HlasnyProfil
        {
            get
            {
                return fHlasnyProfil;
            }

            set
            {
                SetPropertyValue<PIS_HlasnyProfil>(nameof(HlasnyProfil), ref fHlasnyProfil, value);
            }
        }

     
        string fPoznamka;
        /// <summary>
        ///Poznámka
        /// 
        /// </summary>
        [Index(0)]
        [Size(Unlimited)]
        [DevExpress.Xpo.DisplayName(@"Poznámka")]
        public string Poznamka
        {
            get
            {
                return fPoznamka;
            }

            set
            {
                SetPropertyValue<string>(nameof(Poznamka), ref fPoznamka, value);
            }
        }

     
        double fPrutok;
        /// <summary>
        ///Průtok
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Průtok")]
        public double Prutok
        {
            get
            {
                return fPrutok;
            }

            set
            {
                SetPropertyValue<double>(nameof(Prutok), ref fPrutok, value);
            }
        }

     
        GA_CasY fRok;
        /// <summary>
        ///Rok
        /// 
        /// </summary>
        [NoForeignKey]
        [Index(0)]
        public GA_CasY Rok
        {
            get
            {
                return fRok;
            }

            set
            {
                SetPropertyValue<GA_CasY>(nameof(Rok), ref fRok, value);
            }
        }

     
        double fTeplota;
        /// <summary>
        ///Teplota
        /// 
        /// </summary>
        [Index(0)]
        public double Teplota
        {
            get
            {
                return fTeplota;
            }

            set
            {
                SetPropertyValue<double>(nameof(Teplota), ref fTeplota, value);
            }
        }


    }
}
