//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class OdecetVS_sim
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fDatum;
        /// <summary>
        ///Datum
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum")]
        public DateTime Datum
        {
            get
            {
                return fDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value);
            }
        }

     
        decimal fHladina;
        /// <summary>
        ///Hladina
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = N3)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hladina")]
        public decimal Hladina
        {
            get
            {
                return fHladina;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Hladina), ref fHladina, value);
            }
        }

     
        decimal fPrutok;
        /// <summary>
        ///Prutok
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = N3)]
        [Index(1)]
        [DevExpress.Xpo.DisplayName(@"Prutok")]
        public decimal Prutok
        {
            get
            {
                return fPrutok;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Prutok), ref fPrutok, value);
            }
        }

     
        string fPoznamka;
        /// <summary>
        ///Poznamka
        /// 
        /// </summary>
        [System.ComponentModel.DisplayName(Poznámka k simulaci)]
        public string Poznamka
        {
            get
            {
                return fPoznamka;
            }

            set
            {
                SetPropertyValue<string>(nameof(Poznamka), ref fPoznamka, value);
            }
        }

     
        PIS_HlasnyProfil fHlasnyProfil;
        /// <summary>
        ///Hlásný profil
        /// 
        /// </summary>
        [Association(name = OdectySimRefHP)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hlásný profil")]
        public PIS_HlasnyProfil HlasnyProfil
        {
            get
            {
                return fHlasnyProfil;
            }

            set
            {
                SetPropertyValue<PIS_HlasnyProfil>(nameof(HlasnyProfil), ref fHlasnyProfil, value);
            }
        }


    }
}
