//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class ProcessStates
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fDatum;
        /// <summary>
        ///Poslední spuštění
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Poslední spuštění")]
        public DateTime Datum
        {
            get
            {
                return fDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value);
            }
        }

     
        DateTime fDatumNext;
        /// <summary>
        ///Příští spuštění
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Příští spuštění")]
        public DateTime DatumNext
        {
            get
            {
                return fDatumNext;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(DatumNext), ref fDatumNext, value);
            }
        }

     
        string fNazev;
        /// <summary>
        ///Nazev
        /// 
        /// </summary>
        [System.ComponentModel.DisplayName(Název služby)]
        public string Nazev
        {
            get
            {
                return fNazev;
            }

            set
            {
                SetPropertyValue<string>(nameof(Nazev), ref fNazev, value);
            }
        }

     
        string fZdroj;
        /// <summary>
        ///Zdroj
        /// 
        /// </summary>
        [System.ComponentModel.DisplayName(Zdroj dat)]
        public string Zdroj
        {
            get
            {
                return fZdroj;
            }

            set
            {
                SetPropertyValue<string>(nameof(Zdroj), ref fZdroj, value);
            }
        }

     
        e_ProcesState fState;
        /// <summary>
        ///State
        /// 
        /// </summary>
        [System.ComponentModel.DisplayName(Stav)]
        public e_ProcesState State
        {
            get
            {
                return fState;
            }

            set
            {
                SetPropertyValue<e_ProcesState>(nameof(State), ref fState, value);
            }
        }


    }
}
