//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.INF.BO
{
    public partial class Reka
    {
        decimal fDelkaCelkem;
        /// <summary>
        ///Délka celkem
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = #########0.00## km)]
        [ModelDefault(EditMask = N3)]
        [DevExpress.ExpressApp.Model.DetailViewLayout(DalsiUdaje)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Délka celkem")]
        public decimal DelkaCelkem
        {
            get
            {
                return fDelkaCelkem;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(DelkaCelkem), ref fDelkaCelkem, value);
            }
        }

     
        decimal fDelkaCR;
        /// <summary>
        ///Délka v ČR
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = #########0.00## km)]
        [ModelDefault(EditMask = N3)]
        [DevExpress.ExpressApp.Model.DetailViewLayout(DalsiUdaje)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Délka v ČR")]
        public decimal DelkaCR
        {
            get
            {
                return fDelkaCR;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(DelkaCR), ref fDelkaCR, value);
            }
        }

     
        string fHydroPoradi;
        /// <summary>
        ///Hydrologické pořadí
        /// 
        /// </summary>
        [DevExpress.ExpressApp.Model.DetailViewLayout(DalsiUdaje)]
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Hydrologické pořadí")]
        public string HydroPoradi
        {
            get
            {
                return fHydroPoradi;
            }

            set
            {
                SetPropertyValue<string>(nameof(HydroPoradi), ref fHydroPoradi, value);
            }
        }

     
        string fIdentifikator;
        /// <summary>
        ///Identifikátor
        /// 
        /// </summary>
        [DevExpress.ExpressApp.Model.DetailViewLayout(DalsiUdaje)]
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Identifikátor")]
        public string Identifikator
        {
            get
            {
                return fIdentifikator;
            }

            set
            {
                SetPropertyValue<string>(nameof(Identifikator), ref fIdentifikator, value);
            }
        }

     
        decimal fPovodiCR;
        /// <summary>
        ///Povodí v ČR [km2]
        /// 
        /// </summary>
        [km2]
        [DevExpress.ExpressApp.Model.DetailViewLayout(DalsiUdaje)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Povodí v ČR [km2]")]
        public decimal PovodiCR
        {
            get
            {
                return fPovodiCR;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(PovodiCR), ref fPovodiCR, value);
            }
        }


    }
}
