//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class Simulace
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fDatum;
        /// <summary>
        ///Datum a čas
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum a čas")]
        public DateTime Datum
        {
            get
            {
                return fDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value);
            }
        }

     
        double fHladina;
        /// <summary>
        ///Hladina
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = {0:N0} cm)]
        [ModelDefault(EditMask = N0)]
        [ImmediatePostData]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hladina")]
        public double Hladina
        {
            get
            {
                return fHladina;
            }

            set
            {
                SetPropertyValue<double>(nameof(Hladina), ref fHladina, value);
            }
        }

     
        PIS_HlasnyProfil fHlasnyProfil;
        /// <summary>
        ///Hlásný profil
        /// 
        /// </summary>
        [Association(name = HPRefSim)]
        [ImmediatePostData]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hlásný profil")]
        public PIS_HlasnyProfil HlasnyProfil
        {
            get
            {
                return fHlasnyProfil;
            }

            set
            {
                SetPropertyValue<PIS_HlasnyProfil>(nameof(HlasnyProfil), ref fHlasnyProfil, value);
            }
        }

     
        double fPrutok;
        /// <summary>
        ///Průtok
        /// 
        /// </summary>
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Průtok")]
        public double Prutok
        {
            get
            {
                return fPrutok;
            }

            set
            {
                SetPropertyValue<double>(nameof(Prutok), ref fPrutok, value);
            }
        }


    }
}
