//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class TopStavy
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        DateTime fDatum;
        /// <summary>
        ///Datum
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = G)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Datum")]
        public DateTime Datum
        {
            get
            {
                return fDatum;
            }

            set
            {
                SetPropertyValue<DateTime>(nameof(Datum), ref fDatum, value);
            }
        }

     
        PIS_HlasnyProfil fHlasnyProfil;
        /// <summary>
        ///Hlásný profil
        /// 
        /// </summary>
        [Association(name = TopStavyRefHP)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hlásný profil")]
        public PIS_HlasnyProfil HlasnyProfil
        {
            get
            {
                return fHlasnyProfil;
            }

            set
            {
                SetPropertyValue<PIS_HlasnyProfil>(nameof(HlasnyProfil), ref fHlasnyProfil, value);
            }
        }

     
        decimal fHodnota;
        /// <summary>
        ///Hodnota
        /// 
        /// </summary>
        [ModelDefault(DisplayFormat = N3)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Hodnota")]
        public decimal Hodnota
        {
            get
            {
                return fHodnota;
            }

            set
            {
                SetPropertyValue<decimal>(nameof(Hodnota), ref fHodnota, value);
            }
        }


    }
}
