//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class VlastnostObjektu
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        string fHodnotaVlastnosti;
        /// <summary>
        ///Hodnota
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Hodnota")]
        public string HodnotaVlastnosti
        {
            get
            {
                return fHodnotaVlastnosti;
            }

            set
            {
                SetPropertyValue<string>(nameof(HodnotaVlastnosti), ref fHodnotaVlastnosti, value);
            }
        }

     
        string fNazevVlastnosti;
        /// <summary>
        ///Název vlastnosti
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Název vlastnosti")]
        public string NazevVlastnosti
        {
            get
            {
                return fNazevVlastnosti;
            }

            set
            {
                SetPropertyValue<string>(nameof(NazevVlastnosti), ref fNazevVlastnosti, value);
            }
        }

     
        PIS_Objekt fObjekt;
        /// <summary>
        ///Objekt
        /// 
        /// </summary>
        [Association(name = ObjektRefVlastnostObjektu)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Objekt")]
        public PIS_Objekt Objekt
        {
            get
            {
                return fObjekt;
            }

            set
            {
                SetPropertyValue<PIS_Objekt>(nameof(Objekt), ref fObjekt, value);
            }
        }


    }
}
