//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.ExpressApp.Model;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.Validation;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;

namespace GA.PIS.BO
{
    public partial class VObject
    {
        Guid fOID;
        /// <summary>
        ///OID
        /// Primární klíč - Guid
        /// 
        /// </summary>
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        [VisibleInLookupListView(false)]
        [Key(true)]
        public Guid OID
        {
            get
            {
                return fOID;
            }

            set
            {
                SetPropertyValue<Guid>(nameof(OID), ref fOID, value);
            }
        }

     
        string fVObjectName;
        /// <summary>
        ///Název
        /// 
        /// </summary>
        [Index(0)]
        [Size(100)]
        [DevExpress.Xpo.DisplayName(@"Název")]
        public string VObjectName
        {
            get
            {
                return fVObjectName;
            }

            set
            {
                SetPropertyValue<string>(nameof(VObjectName), ref fVObjectName, value);
            }
        }

     
        PIS_HlasnyProfil fVodomernaStanice;
        /// <summary>
        ///Vodoměrná stanice
        /// 
        /// </summary>
        [Association(name = HPRefVOBJ)]
        [RuleRequiredField(RuleRequiredField for PIS_VObject.VodomernaStanice)]
        [Index(0)]
        [DevExpress.Xpo.DisplayName(@"Vodoměrná stanice")]
        public PIS_HlasnyProfil VodomernaStanice
        {
            get
            {
                return fVodomernaStanice;
            }

            set
            {
                SetPropertyValue<PIS_HlasnyProfil>(nameof(VodomernaStanice), ref fVodomernaStanice, value);
            }
        }


    }
}
